apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
  namespace: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: canary
  template:
    metadata:
      labels:
        app: my-app
        version: canary
    spec:
      containers:
      - name: my-app-container
        image: your-image:canary
        ports:
        - containerPort: 80