apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-deployment
  namespace: canary-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: stable
  template:
    metadata:
      labels:
        app: my-app
        version: stable
    spec:
      containers:
      - name: my-app-container
        image: your-image:stable
        ports:
        - containerPort: 80